### ISSUE TITLE
Problem with rhpkg new-sources during OSBS build on RHEL/CentOS/SL (concreate 1.3.0)

### ISSUE THREAD

**Issue by pszubiak** [jboss-container-images/concreate#140]
I hit following problem during OSBS build of processerver6 and decisionserver6 on Scientific Linux 7.3 x86_64. Maybe it's worth to mention that OSBS build of kieserver6 is fine.

```yaml
schema_version: 1

name: "jboss-processserver-6/processserver64-openshift"
version: "1.1"
description: "Platform for executing business rules on JBoss BPMS Intelligent Process Server 6.4."
from: "jboss-kieserver-6/kieserver64-openshift:1.1"
labels:
    - name: "io.k8s.description"
      value: "Platform for executing business rules on JBoss BPMS Intelligent Process Server 6.4."
    - name: "io.k8s.display-name"
      value: "JBoss BPMS Intelligent Process Server 6.4"
    - name: "io.openshift.tags"
      value: "builder,processserver,processserver6"
envs:
    - name: "KIE_SERVER_BPM_UI_DISABLED"
      value: "true"
      description: "The BPM UI capability is disabled in this image."
    - name: "KIE_SERVER_BRP_DISABLED"
      value: "true"
      description: "The BRP capability is disabled in this image."
    - name: "JBOSS_PRODUCT"
      value: "processserver"
    - name: "JBOSS_PROCESSSERVER_VERSION"
      value: "6.4.7.GA"
    - name: "PRODUCT_VERSION"
      value: "6.4.7.GA"
run:
      user: 185
osbs:
      repository:
            name: jboss-processserver-6-docker
            branch: ce-1.1-openshift-processserver-6.4-jdk-8-rhel-7
```
```
$ concreate build --build-engine=osbs
2017-11-24 20:21:24,313 concreate    INFO     Initializing image descriptor...
2017-11-24 20:21:24,313 concreate    INFO     Handling artifacts...
2017-11-24 20:21:24,329 concreate    INFO     Rendering Dockerfile...
2017-11-24 20:21:24,370 concreate    INFO     Using OSBS builder to build the image.
2017-11-24 20:21:24,583 concreate    INFO     Pulling latest changes in repo jboss-processserver-6-docker...
Could not chdir to home directory /home/remote/pszubiak: No such file or directory
2017-11-24 20:21:31,714 concreate    INFO     Removing old 'repos' directory
2017-11-24 20:21:31,714 concreate    INFO     Removing old 'modules' directory
fatal: pathspec 'repos' did not match any files
fatal: pathspec 'modules' did not match any files
2017-11-24 20:21:31,730 concreate    INFO     Updating lookaside cache...
usage: rhpkg new-sources [-h] files [files ...]
rhpkg new-sources: error: too few arguments
Traceback (most recent call last):
  File "/usr/bin/concreate", line 9, in <module>
    load_entry_point('concreate==1.3.0', 'console_scripts', 'concreate')()
  File "/usr/lib/python2.7/site-packages/concreate/cli.py", line 187, in run
    Concreate().parse().run()
  File "/usr/lib/python2.7/site-packages/concreate/cli.py", line 156, in run
    builder.build(self.args)
  File "/usr/lib/python2.7/site-packages/concreate/builders/osbs.py", line 89, in build
    self.update_lookaside_cache()
  File "/usr/lib/python2.7/site-packages/concreate/builders/osbs.py", line 78, in update_lookaside_cache
    subprocess.check_output(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['rhpkg', 'new-sources']' returned non-zero exit status 2
```

**Comment by dbecvarik** [comment]
fixed by #141
